# -*- coding: utf-8 -*-
"""PR_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTJ5wsrxMHZdNLa0mkiErBmFhTV-rdno
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
data = iris.data

data

# Standardize the data (scaling)
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# Initialize an empty list to store the values of the within-cluster sum of squares (WCSS)
wcss = []

# Determine the number of clusters using the elbow method
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=30)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)

# Plot the elbow graph
plt.figure(figsize=(8, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS (Within-Cluster Sum of Squares)')
plt.grid()
plt.show()

wcss

